name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26
          cache: maven

      - name: Setup Maven auth
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>

              <server>
                <id>github-commons</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>

              <server>
                <id>github-validation</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${GITHUB_TOKEN}</password>
              </server>

            </servers>
          </settings>
          EOF
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.OMNIXYS_TOKEN }}

      - name: Build & Test
        run: mvn -B test